application: casaknudsen2
version: 2-1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /(.*\.html)$
  static_files: static/\1
  upload: static/.*\.(html)$

- url: /.*
  script: _go_app


